name: Tests for CI 

on:
  pull_request:
    branches:
      - main

jobs:
  Tests-for-CI:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Repository Code
    - name: Checkout Repository Code
      uses: actions/checkout@v3

    # Step 2: Set Up Python Environment
    - name: Set Up Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Step 3: Install Project Dependencies
    - name: Install Project Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    # Step 4: Execute Unit Tests
    - name: Execute Unit Tests
      run: |
        pytest tests/test_unit.py

    # Step 5: Execute Integration Tests
    - name: Execute Integration Tests
      run: |
        pytest tests/test_integration.py
