name: Tests for CI

on:
  pull_request:
    branches:
      - main

jobs:
  Tests-for-CI:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Repository Code
    - name: Checkout Repository Code
      uses: actions/checkout@v3

    # Step 2: Set Up Python Environment
    - name: Set Up Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install Project Dependencies
    - name: Install Project Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    # Step 4: Add Poetry Virtual Environment to PATH
    - name: Add Poetry Virtual Environment to PATH
      run: |
        echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

    # Step 5: Run All Tests
    - name: Run All Tests
      run: |
        pytest tests/
